// <auto-generated />
using EF.Hierarchy.TPT;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF.Hierarchy.TPT.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20240910202802_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF.Hierarchy.TPT.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EF.Hierarchy.TPT.Entities.Alumno", b =>
                {
                    b.HasBaseType("EF.Hierarchy.TPT.Entities.Persona");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("EF.Hierarchy.TPT.Entities.Profesor", b =>
                {
                    b.HasBaseType("EF.Hierarchy.TPT.Entities.Persona");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("EF.Hierarchy.TPT.Entities.Alumno", b =>
                {
                    b.HasOne("EF.Hierarchy.TPT.Entities.Persona", null)
                        .WithOne()
                        .HasForeignKey("EF.Hierarchy.TPT.Entities.Alumno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF.Hierarchy.TPT.Entities.Profesor", b =>
                {
                    b.HasOne("EF.Hierarchy.TPT.Entities.Persona", null)
                        .WithOne()
                        .HasForeignKey("EF.Hierarchy.TPT.Entities.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
